name: Build Images

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_base_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: ./Spot  # Adjust context if necessary
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main

  build_image:
    runs-on: ubuntu-latest
    needs: build_base_image  # Ensures this job runs after the base image is built
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push new image
        uses: docker/build-push-action@v3
        with:
          context: ./Spot  # Ensure this points to the correct directory
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
